### ISSUE TITLE
[EPIC] - chat widget live & operational on openline.ai

### ISSUE THREAD

**Issue by matt-brown-OL** [openline-ai/openline-customer-support-widget#8]
- [ ] [Rework websockets](https://github.com/openline-ai/openline-agent-platform-frontend/issues/8)
- [ ] [Integrate event tracker w/ widget](https://github.com/openline-ai/openline-customer-os/issues/21)
- [ ] [Deploy customer support platform](https://github.com/openline-ai/openline-customer-support-platform/issues/23)
- [ ] [Message store API improvements](https://github.com/openline-ai/openline-customer-support-platform/issues/24)
- [ ] [Secure agent API](https://github.com/openline-ai/openline-customer-support-platform/issues/25)
- [ ] [Secure channels API](https://github.com/openline-ai/openline-channels/issues/18)
- [ ] [Move email to Amazon SES](https://github.com/openline-ai/openline-channels/issues/15)
- [ ] [Deploy real-time comms app to production](https://github.com/openline-ai/openline-customer-support-platform/issues/16)
- [ ] [Add webrtc support to widget/agent app](https://github.com/openline-ai/openline-agent-platform-frontend/issues/5)
- [ ] [Integrate openline-event-tracker with agent app](https://github.com/openline-ai/openline-customer-os/issues/20)
- [ ] [Chat from slack to webchat](https://github.com/openline-ai/openline-customer-support-platform/issues/22)
- [ ] [Push webchat into slack](https://github.com/openline-ai/openline-customer-support-platform/issues/11)
- [ ] [Ability to log a communication against a contact in customerOS](https://github.com/openline-ai/openline-crm/issues/7)
- [ ] [Post-chat transcript delivery](https://github.com/openline-ai/openline-customer-support-platform/issues/12)
- [ ] [Chat no long in session, email](https://github.com/openline-ai/openline-customer-support-platform/issues/19)
- [ ] [Log all customer comms against customerOS](https://github.com/openline-ai/openline-customer-support-platform/issues/15)

**Comment by mattbr0wn** [comment]
moving  https://github.com/openline-ai/openline-customer-support-platform/issues/24 to Oasis launch epic

**Comment by mattbr0wn** [comment]
moving https://github.com/openline-ai/openline-customer-support-platform/issues/15 to Oasis launch epic

**Comment by mattbr0wn** [comment]
moving https://github.com/openline-ai/openline-customer-os/issues/20 to Oasis launch epic
